/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.7
 * Generated at: 2023-09-26 14:56:26 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.frontend;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("file:/C:/Users/umami/.m2/repository/lk/callidora/jsp/jsp-template-inheritance/1.0.1/jsp-template-inheritance-1.0.1.jar", Long.valueOf(1692244324806L));
    _jspx_dependants.put("jar:file:/C:/Users/umami/.m2/repository/lk/callidora/jsp/jsp-template-inheritance/1.0.1/jsp-template-inheritance-1.0.1.jar!/META-INF/jsp-inheritance.tld", Long.valueOf(1692219220000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      if (_jspx_meth_layout_005fextends_005f0(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_layout_005fextends_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  layout:extends
    lk.callidora.jsp.inheritance.ExtendsTag _jspx_th_layout_005fextends_005f0 = new lk.callidora.jsp.inheritance.ExtendsTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_layout_005fextends_005f0);
    try {
      _jspx_th_layout_005fextends_005f0.setJspContext(_jspx_page_context);
      // /WEB-INF/views/frontend/home.jsp(2,0) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_layout_005fextends_005f0.setName("base");
      _jspx_th_layout_005fextends_005f0.setJspBody(new Helper( 0, _jspx_page_context, _jspx_th_layout_005fextends_005f0, null));
      _jspx_th_layout_005fextends_005f0.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_layout_005fextends_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_layout_005fput_005f0(jakarta.servlet.jsp.tagext.JspTag _jspx_parent, jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  layout:put
    lk.callidora.jsp.inheritance.PutTag _jspx_th_layout_005fput_005f0 = new lk.callidora.jsp.inheritance.PutTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_layout_005fput_005f0);
    try {
      _jspx_th_layout_005fput_005f0.setJspContext(_jspx_page_context);
      _jspx_th_layout_005fput_005f0.setParent(_jspx_parent);
      // /WEB-INF/views/frontend/home.jsp(6,2) name = block type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_layout_005fput_005f0.setBlock("contents");
      _jspx_th_layout_005fput_005f0.setJspBody(new Helper( 1, _jspx_page_context, _jspx_th_layout_005fput_005f0, null));
      _jspx_th_layout_005fput_005f0.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_layout_005fput_005f0);
    }
    return false;
  }

  private class Helper
      extends org.apache.jasper.runtime.JspFragmentHelper
  {
    private jakarta.servlet.jsp.tagext.JspTag _jspx_parent;
    private int[] _jspx_push_body_count;

    public Helper( int discriminator, jakarta.servlet.jsp.JspContext jspContext, jakarta.servlet.jsp.tagext.JspTag _jspx_parent, int[] _jspx_push_body_count ) {
      super( discriminator, jspContext, _jspx_parent );
      this._jspx_parent = _jspx_parent;
      this._jspx_push_body_count = _jspx_push_body_count;
    }
    public boolean invoke0( jakarta.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("  ");
      if (_jspx_meth_layout_005fput_005f0(_jspx_parent, _jspx_page_context))
        return true;
      out.write('\r');
      out.write('\n');
      return false;
    }
    public boolean invoke1( jakarta.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <!-- search bar -->\r\n");
      out.write("        <div class=\"col-12 justify-content-center border-bottom border-2 border-warning bg-light mb-3\">\r\n");
      out.write("          <div class=\"row mb-1\">\r\n");
      out.write("            <div class=\"col-12 col-lg-2 text-center\"><h1 class=\"text-success fw-bold mt-lg-2\"></h1></div>\r\n");
      out.write("            <!-- <div class=\"offset-lg-1 col-12 col-lg-1 logoimg\"></div> -->\r\n");
      out.write("            <div class=\"col-8 col-lg-6\">\r\n");
      out.write("              <div class=\"input-group input-group-lg mt-3 mb-3\">\r\n");
      out.write("                <input type=\"text\" class=\"form-control\" aria-label=\"Text input with dropdown button\" id=\"basic_search_txt\">\r\n");
      out.write("\r\n");
      out.write("                <select class=\"btn btn-outline-success\" id=\"basic_search_select\">\r\n");
      out.write("                  <option value=\"0\">Category</option>\r\n");
      out.write("                  <option class=\"dropdown-item\"></option>\r\n");
      out.write("                </select>\r\n");
      out.write("\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-2 d-grid gap-2\">\r\n");
      out.write("              <button class=\"btn btn-success mt-3 searchbtn\" onclick=\"basicSearch(1);\">Search</button>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-2 mt-4\">\r\n");
      out.write("              <a class=\"link-dark link1\" href=\"#\">Advanced</a>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- search bar -->\r\n");
      out.write("        <!-- <hr class=\"hrbreak1\" /> -->\r\n");
      out.write("        <!-- slide -->\r\n");
      out.write("        <div class=\"col-12 d-none d-lg-block border-bottom border-2 border-warning\" id=\"imgslide\">\r\n");
      out.write("          <div class=\"row mb-3\">\r\n");
      out.write("            <div id=\"carouselExampleCaptions\" class=\"offset-2 col-8 carousel slide\" data-bs-ride=\"carousel\">\r\n");
      out.write("              <div class=\"carousel-indicators\">\r\n");
      out.write("                <button type=\"button\" data-bs-target=\"#carouselExampleCaptions\" data-bs-slide-to=\"0\" class=\"active\" aria-current=\"true\" aria-label=\"Slide 1\"></button>\r\n");
      out.write("                <button type=\"button\" data-bs-target=\"#carouselExampleCaptions\" data-bs-slide-to=\"1\" aria-label=\"Slide 2\"></button>\r\n");
      out.write("                <button type=\"button\" data-bs-target=\"#carouselExampleCaptions\" data-bs-slide-to=\"2\" aria-label=\"Slide 3\"></button>\r\n");
      out.write("                <button type=\"button\" data-bs-target=\"#carouselExampleCaptions\" data-bs-slide-to=\"3\" aria-label=\"Slide 4\"></button>\r\n");
      out.write("                <button type=\"button\" data-bs-target=\"#carouselExampleCaptions\" data-bs-slide-to=\"4\" aria-label=\"Slide 5\"></button>\r\n");
      out.write("                <button type=\"button\" data-bs-target=\"#carouselExampleCaptions\" data-bs-slide-to=\"5\" aria-label=\"Slide 6\"></button>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"carousel-inner\">\r\n");
      out.write("                <div class=\"carousel-item active\">\r\n");
      out.write("                  <img src=\"new resources/slider images/business-layout-full-page-3778.jpg\" class=\"d-block posterimg1\">\r\n");
      out.write("                  <div class=\"carousel-caption d-none d-md-block postercaption\">\r\n");
      out.write("                    <h5 class=\"postertitle\">Welcome to Greenelec</h5>\r\n");
      out.write("                    <p class=\"postertxt\">The World Best Online Store By One Click.</p>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"carousel-item\">\r\n");
      out.write("                  <img src=\"new resources/slider images/Top-5-Best-Mobile-Phones-Under-12000-Budget-Best-768x432.jpg\" class=\"d-block posterimg1\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"carousel-item\">\r\n");
      out.write("                  <img src=\"new resources/slider images/Preview-Galaxy-A30-Galaxy-A50-flashfly-800x417.jpg\" class=\"d-block posterimg1\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"carousel-item\">\r\n");
      out.write("                  <img src=\"new resources/slider images/Rb00d7967275020b1ee257b67db03de92.jpg\" class=\"d-block posterimg1\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"carousel-item\">\r\n");
      out.write("                  <img src=\"new resources/slider images/R (5).jpg\" class=\"d-block posterimg1\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"carousel-item\">\r\n");
      out.write("                  <img src=\"new resources/slider images/R.jpg\" class=\"d-block posterimg1\">\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("              <button class=\"carousel-control-prev\" type=\"button\" data-bs-target=\"#carouselExampleCaptions\" data-bs-slide=\"prev\">\r\n");
      out.write("                <span class=\"carousel-control-prev-icon\" aria-hidden=\"true\"></span>\r\n");
      out.write("                <span class=\"visually-hidden\">Previous</span>\r\n");
      out.write("              </button>\r\n");
      out.write("              <button class=\"carousel-control-next\" type=\"button\" data-bs-target=\"#carouselExampleCaptions\" data-bs-slide=\"next\">\r\n");
      out.write("                <span class=\"carousel-control-next-icon\" aria-hidden=\"true\"></span>\r\n");
      out.write("                <span class=\"visually-hidden\">Next</span>\r\n");
      out.write("              </button>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- slide -->\r\n");
      out.write("        <div id=\"basicresult\"></div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"col-12 mt-3\">\r\n");
      out.write("          <a class=\"link-dark link2\" href=\"#\"><?php echo $c[\"name\"]; ?></a>&nbsp;&nbsp;\r\n");
      out.write("          <a class=\"link-dark link3\" href=\"#\">See All &rightarrow;</a>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <div class=\"col-12 mb-5\">\r\n");
      out.write("          <div class=\"row border border-success\">\r\n");
      out.write("            <div class=\"col-12 col-lg-12\">\r\n");
      out.write("              <div class=\"row justify-content-center\">\r\n");
      out.write("                <!-- card -->\r\n");
      out.write("                <div class=\"card col-6 col-lg-2 mt-1 mb-1 ms-1\" style=\"width: 18.5rem;\">\r\n");
      out.write("                  <img src=\"\" class=\"cardTopImg\" />\r\n");
      out.write("                  <hr/>\r\n");
      out.write("                  <div class=\"card-body\">\r\n");
      out.write("                    <h5 class=\"card-title\"> <span class=\"badge\" style=\"background-color: orange;\">New</span></h5>\r\n");
      out.write("                    <span class=\"card-text text-primary\">Rs. <?php echo $prod[\"price\"]; ?> .00</span><br />\r\n");
      out.write("                    <span class=\"card-text text-warning\"><b>In Stock</b></span>\r\n");
      out.write("                    <input type=\"number\" value=\"1\" class=\"form-control mb-1\" min=\"0\" id=\"qtytxt\" />\r\n");
      out.write("                    <a href=\"#\" class=\"btn btn-success\">Buy Now</a>\r\n");
      out.write("                    <a class=\"btn btn-primary\" onclick=\"addToCart();\">Add Cart</a>\r\n");
      out.write("                    <a class=\"btn btn-secondary\" onclick=\"addToWatchlist();\"><i class=\"bi bi-heart-fill fs-6\"></i></a>\r\n");
      out.write("\r\n");
      out.write("                    <span class=\"card-text text-danger\"><b>Out of Stock</b></span>\r\n");
      out.write("                    <input type=\"number\" value=\"1\" class=\"form-control mb-1\" min=\"0\" disabled />\r\n");
      out.write("                    <a class=\"btn btn-dark\" disabled>Buy Now</a>\r\n");
      out.write("                    <a href=\"#\" class=\"btn btn-dark\" disabled>Add Cart</a>\r\n");
      out.write("                    <a class=\"btn btn-dark\" disabled><i class=\"bi bi-heart-fill fs-6\"></i></a>\r\n");
      out.write("\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- card -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- product view -->\r\n");
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("  ");
      return false;
    }
    public void invoke( java.io.Writer writer )
      throws jakarta.servlet.jsp.JspException
    {
      jakarta.servlet.jsp.JspWriter out = null;
      if( writer != null ) {
        out = this.jspContext.pushBody(writer);
      } else {
        out = this.jspContext.getOut();
      }
      try {
        Object _jspx_saved_JspContext = this.jspContext.getELContext().getContext(jakarta.servlet.jsp.JspContext.class);
        this.jspContext.getELContext().putContext(jakarta.servlet.jsp.JspContext.class,this.jspContext);
        switch( this.discriminator ) {
          case 0:
            invoke0( out );
            break;
          case 1:
            invoke1( out );
            break;
        }
        jspContext.getELContext().putContext(jakarta.servlet.jsp.JspContext.class,_jspx_saved_JspContext);
      }
      catch( java.lang.Throwable e ) {
        if (e instanceof jakarta.servlet.jsp.SkipPageException)
            throw (jakarta.servlet.jsp.SkipPageException) e;
        throw new jakarta.servlet.jsp.JspException( e );
      }
      finally {
        if( writer != null ) {
          this.jspContext.popBody();
        }
      }
    }
  }
}
